"""modified meal table

Revision ID: c024b9c07dad
Revises: ddfac3eb7c82
Create Date: 2020-07-14 13:44:44.865818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c024b9c07dad'
down_revision = 'ddfac3eb7c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    op.add_column('meal', sa.Column('food_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'food_ids')
    op.create_table('meals',
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name='meals_food_id_fkey'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], name='meals_meal_id_fkey'),
    sa.PrimaryKeyConstraint('meal_id', 'food_id', name='meals_pkey')
    )
    # ### end Alembic commands ###
